name: Test
on:
  - push
  - pull_request
jobs:
  feature:
    name: Feature
    strategy:
      fail-fast: false
      matrix:
        service:
          # - almalinux-8
          - centos-7
          - debian-bullseye
          - ubuntu-bionic
          - ubuntu-focal
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y -V \
            curl \
            gtk-doc-tools \
            intltool \
            lsb-release
          curl \
            --silent \
            --location \
            https://raw.github.com/clear-code/cutter/master/data/travis/setup.sh | sh
      - run: ./autogen.sh
      - run: docker-compose build ${{ matrix.service }}
      - run: docker-compose run --rm ${{ matrix.service }}

  distribution:
    name: Distribution
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y -V \
            curl \
            gtk-doc-tools \
            intltool \
            lsb-release
          sudo gem install \
            fast_gettext \
            rdtool
      - run: ./autogen.sh
      - run: mkdir -p ../milter-manager.build
      - name: Configure
        run: |
          ../milter-manager/configure \
            --enable-gtk-doc \
            --with-bundled-ruby-glib2 \
            --with-bundled-ruby-gobject-introspection \
            --with-bundled-ruby-gio2
        working-directory: ../milter-manager.build
      - run: make -j$(nproc)
        working-directory: ../milter-manager.build
      - run: make distcheck
        working-directory: ../milter-manager.build
      - name: Show test/tool/ log
        if: failure()
        run: |
          cat ../milter-manager.build/milter-manager-*/_build/sub/test/tool/test-suite.log
      - name: Show test/ log
        if: failure()
        run: |
          cat ../milter-manager.build/milter-manager-*/_build/sub/test/test-suite.log
